name: Test

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{matrix.ruby}} ${{matrix.gemfile}} ${{matrix.server}} ${{matrix.endpoint}}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
      RACK_CONFORM_SERVER: ${{matrix.server}}
      RACK_CONFORM_ENDPOINT: ${{matrix.endpoint}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.1"
            gemfile: "gems/falcon-v0-rack-v2.rb"
            server: "falcon"
            endpoint: "https://localhost:9292"
          - ruby: "3.1"
            gemfile: "gems/falcon-v0-rack-v3.rb"
            server: "falcon"
            endpoint: "https://localhost:9292"
          - ruby: "2.7"
            gemfile: "gems/puma-v4-rack-v2.rb"
            server: "puma"
            endpoint: "http://localhost:9292"
          - ruby: "3.1"
            gemfile: "gems/puma-v5-rack-v2.rb"
            server: "puma"
            endpoint: "http://localhost:9292"
    
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 10
      run: bundle exec bake test
    
    - uses: actions/upload-artifact@v3
      with:
        name: Logs
        path: "*.log"
